In [20]:
l1=[1,2,3,4,5,6,7,8,9]
value_of_p=0.6


for i in range(0,len(l1)):
    if(i==4):
        continue
    else:
        #print("---------"+str(i)+"------"+str(l1[i]))
        #print(abs(l1[4]-l1[i]))
        l1[i]=1/abs(l1[i]-l1[4])

#print(l1)
center_pos=0
if(len(l1)%2==0):
    center_pos=len(l1)/2
else:
    center_pos=int((len(l1)-1)/2)
    
l1[center_pos]=0

#print(l1)


sum_total=sum(l1)

#print("SUm total is:"+str(sum_total))
            
for i in range(0,len(l1)):
    if(i==4):
        l1[i]=value_of_p
    else:
        l1[i]=((1-value_of_p)*(l1[i]/sum_total))

        
print(l1)
#sum_total=sum(l1)
#print("SUm total is:"+str(sum_total))

for i in range(0,len(l1)):
    

SUm total is:4.166666666666666
[0.024000000000000007, 0.032, 0.048000000000000015, 0.09600000000000003, 0.6, 0.09600000000000003, 0.048000000000000015, 0.032, 0.024000000000000007]
SUm total is:1.0000000000000002


In [33]:
import numpy as np

def Gradient_Inverse_Filter(array):
        
        final_image=[]
        filter_array = array.flatten()
        flattenarray = array.flatten()
        #print(flattenarray)
        value_of_p=0.5


        for i in range(0,len(flattenarray)):
            if(i==4):
                continue
            else:
                #print("---------"+str(i)+"------"+str(flattenarray[i]))
                #print(abs(flattenarray[4]-flattenarray[i]))
                flattenarray[i]=1/abs(flattenarray[i]-flattenarray[4])

       # print(flattenarray)
        center_pos=0
        if(len(flattenarray)%2==0):
            center_pos=len(flattenarray)/2
        else:
            center_pos=int((len(flattenarray)-1)/2)
    
        flattenarray[center_pos]=0

        print(flattenarray)


        sum_total=sum(flattenarray)

        #print("SUm total is:"+str(sum_total))
            
        for i in range(0,len(flattenarray)):
            if(i==4):
                flattenarray[i]=value_of_p
            else:
                flattenarray[i]=((1-value_of_p)*(flattenarray[i]/sum_total))

        
        print(flattenarray)
        Convolve_array=np.multiply(filter_array,flattenarray)
        print(Convolve_array)
        Gradient_Inverse_value=sum(Convolve_array)
        print(Gradient_Inverse_value)
        #return Gradient_Inverse_value
        
        
        
        
        
        
a=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(a, dtype=float)
print(a)
Gradient_Inverse_Filter(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[0.25       0.33333333 0.5        1.         0.         1.
 0.5        0.33333333 0.25      ]
[0.03 0.04 0.06 0.12 0.5  0.12 0.06 0.04 0.03]
[0.03 0.08 0.18 0.48 2.5  0.72 0.42 0.32 0.27]
5.000000000000001


In [28]:
a=[0,0,0,1,2,3]
a=np.array(a, dtype=float)
print(a.shape)

(6,)


In [43]:
import numpy as np
import cv2

# Load an color image in grayscale
a="luffy.jpg"
img = cv2.imread(a,cv2.IMREAD_UNCHANGED)
print(img[0])



[[[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [252 252 252]
  [244 244 244]
  [226 205 208]
  [231 239 238]
  [224 251 247]
  [229 237 236]
  [248 218 223]
  [245 198 206]
  [230 203 207]
  [233 233 233]
  [249 227 239]
  [246 254 255]
  [233 239 246]
  [238 204 221]
  [184 149 139]
  [255 255 247]
  [108  59 241]
  [ 41  14 124]
  [ 42   4  32]
  [ 83  32  29]
  [ 41  17   0]
  [ 66  20 210]
  [ 72  39 227]
  [ 95  55 137]
  [ 82  33  55]
  [ 86  38  74]
  [ 79  34  60]
  [ 89  44  70]
  [ 86  38  66]
  [ 78  33  60]
  [ 75  35  60]
  [ 54  22  39]
  [ 29  